### ISSUE TITLE
io-board.pro library paths are fixed to D:/Sudharshan/Projects/kerbalcontrol-pcb/libraries

### ISSUE THREAD

**Issue by DanielTBrown** [solderneer/KerbalKontrol#11]
In the KiCAD project file electronics/io-board/io-board.pro, three of the libraries have fixed paths that begin with D:/Sudharshan/Projects/kerbalcontrol-pcb/libraries. KiCAD issues an error when opening the schematic io-board.sch.

![screenshot from 2017-08-01 13-49-18](https://user-images.githubusercontent.com/12141206/28846437-4848a6ee-76c0-11e7-98b4-c33cacac839f.png)

**Comment by solderneer** [comment]
Yep, thanks for that. The same problem probably exists for the main board as well...

**Comment by solderneer** [comment]
It should be fixed now. moved to a relative general library path instead of adding each lib manually
